### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pppbb** [jp7677/dxvk-nvapi#148]
How to use dxvk-nvapi with wine-staging?
How to configure environment?
I can't get it to work.

**Comment by jp7677** [comment]
Please see https://github.com/jp7677/dxvk-nvapi#wine and https://github.com/jp7677/dxvk-nvapi/wiki/Tips-and-tricks-for-usage-with-DXVK-NVAPI

**Comment by pppbb** [comment]
The thing is i followed those instructions carefully and still i can't get it to work with wine staging.

**Comment by jp7677** [comment]
I would advise you to use Steam or one of the other launchers. Setting DXVK-NVAPI up on wine/wine-staging manually requires a more detailed knowledge of that ecosystem since the road can be somewhat bumpier. Considering your request for a more general introduction, using a launcher that does this for you might be easier.

**Comment by pppbb** [comment]
Thank you for the reply. Unfortunately Lutris launcher also didn't help. I give up for now.

**Comment by jp7677** [comment]
Sorry to hear that. Feel free of course to ask a specific question of post detailed information where you are stuk and I’m happy to help. It’s just I don’t know where to start when no information whatsoever is provided, except “it doesn’t work”.

**Comment by jp7677** [comment]
Feel free to reopen if you want to come back to this.
