### ISSUE TITLE
Logging improvements 

### ISSUE THREAD

**Issue by jp7677** [jp7677/dxvk-nvapi#36]
Once most PRs are merged and things have settled a bit we should
- ~replace all string literals about function names with `__func__`~
- ~Think about disabling the logging by default (may be except the version statement on initialize)~

**Comment by SveSop** [comment]
If i were to have a "wishlist" when it comes to logging, it would be:

`DXVK_NVAPI_LOG_LEVEL=` (ie. "not set" and the default) - Would provide basic log - version/initialize and maybe 1 line per functioncall. (Not too far away from what is the logging today).
`DXVK_NVAPI_LOG_LEVEL=none` = Completely silent
`DXVK_NVAPI_LOG_LEVEL=debug` = Actually log every call - even if it means slowdowns, as it would be used for pure debugging purposes. I actually miss that from the logs today, cos it would be nice to actually see if an app "spams" a certain function over and over like `NvAPI_D3D11_SetDepthBoundsTest`. For debugging purposes, i would actually like to see "all calls", where it kinda seems like it does not now.

I actually did some tests comparing my nvapi-standalone project with DXVK-NVAPI when turning off all logging, and by constantly calling 1 function in a loop x 10000. With logging on `WINEDEBUG=-all, +nvapi` for nvapi-standalone, the logging took some seconds to complete, but with `WINEDEBUG=-all` it was completed in less than a second. (It also completed in less than a second on windows).... however, even with `DXVK_NVAPI_LOG_LEVEL=none` DXVK-NVAPI seemed to spend the same time completing as it did without setting `DXVK_NVAPI_LOG_LEVEL`.

This was with a call without the `static bool alreadyLoggedOk` (and other) functions, so it DID seem to me like using `DXVK_NVAPI_LOG_LEVEL=none` did not actually releave the slowdown caused by extensive logging - Kind of like just piping the log to /dev/null will not really make the library do "less work" in a sense.

I can try make an example thing out of this if you are interested in studying this peculiarity a bit more? (Been a while since i messed with it, but I can see if i manage to recreate this).

**Comment by jp7677** [comment]
Logging is now disabled by default since https://github.com/jp7677/dxvk-nvapi/commit/4d498bfd1c591058d8c0d4d60558dfc5f2d685ea

**Comment by jp7677** [comment]
@SveSop could you provide a small sample program that demonstrates the behavior you are seeing? You might also try to comment the log statements in the source code of `dxvk-nvapi` to see if the logging really is the culprit.

**Comment by vityafx** [comment]
I know it doesn't do much, but I understand that someone had to do this someday anyway. Why not me? https://github.com/jp7677/dxvk-nvapi/pull/41

**Comment by SveSop** [comment]
@jp7677 

I would assume this is due to the way C++ print to console perhaps? since it is not using WINEDEBUG function from WINE and the internal wine logging. Eg. `WINEDEBUG=-all` will still output dxvk-nvapi log lines to console, unless you specify `DXVK_NVAPI_LOG_LEVEL=none`

Might not be possible to change that behavior since it is not "wine" that is outputting the log?

Doing `wine ./logtest.exe > /dev/null 2>&1` on the attached binary takes appx 5 seconds without specifying `DXVK_NVAPI_LOG_LEVEL=none`. Making the output log to file with `DXVK_NVAPI_LOG_PATH` does not cost any more time, so it seems as it is outputting to console that is very slow.

On "staging nvapi" it takes less than 1 second with `WINEDEBUG=-all,+nvapi`, and the console outputs 10K lines of text in less than 1 second using WINEDEBUG.

Doing `wine ./logtest.exe` without piping to /dev/null takes 29 seconds according tho the "timer" i added when using dxvk-nvapi. 

On the calls where you have the "alreadyLogged" functions, this will not happen, as the log will only output 1 incident of the call regardless of how many calls are made.

The reason i was fiddling with this was to see if there would be a possibility to implement `DXVK_NVAPI_LOG_LEVEL=debug` option, to actually log ALL calls. As it is now, it will not do that for the calls with the "alreadyLogged" funcions, and if you are to lets say verify why a certain call is causing slowdowns (excessive spamming of a function), dxvk-nvapi will only indicate that 1 single call is made
[logtest.exe.gz](https://github.com/jp7677/dxvk-nvapi/files/7231392/logtest.exe.gz)
.

**Comment by jp7677** [comment]
Can you provide the source of your logtest executable?

**Comment by SveSop** [comment]
Basically just a trimmed down version of [https://github.com/SveSop/nvtt](https://github.com/SveSop/nvtt) where i remove almost all functions but this:

```
    // Get adaptername for board. Simple text string.
    time_t begin = time(NULL);
    for(int i = 0; i < 10000; i++){
      if(NvGetName && NvGetName(hdlGPU[0], sysname) != NVAPI_OK){
        printf("NvAPI_GPU_GetFullName not available!\n");
      }
    }
    time_t end = time(NULL);
    printf("Name: %s\n", sysname);

    printf("Time to complete 10K calls of NvAPI_GPU_GetFullName: %ld seconds\n", (end - begin));

```
I do not know of any app that does extreme amounts of spamming like this (10K calls asap), so it is somewhat far fetched that it should happen LIKE this ofc. I was just interested in figuring out why it was such a difference in time spent.

**Comment by jp7677** [comment]
> On the calls where you have the "alreadyLogged" functions, this will not happen, as the log will only output 1 incident of the call regardless of how many calls are made.

I'm trying to sort a bit what you wrote.
So DXVK-NVAPI's performance is only somewhat lower for methods that always print logging, but even when logging is off, there is still a penalty compared to nvapi from wine staging?
Does the `alreadyLogged` construction mitigates this? So if you would add `alreadyLogged` to `NvAPI_GPU_GetFullName`, is the penalty gone?

**Comment by SveSop** [comment]
It does not cause this behavior when using `DXVK_NVAPI_LOG_LEVEL=none` (Finish in less than 1 second), so i must have been remembering that wrong. Not able to reproduce the slowdown when logging actually is disabled.

If however logging is enabled, there is a considerable penalty to the output vs. using WINEDEBUG like wine does. Why would the C++ implementation in dxvk-nvapi spend a lot longer time outputting to console? (I did tests where i removed `alreadyLogged` functions to a call, and experienced upwards to 37 seconds vs. WINEDEBUG spending < 1 second).

Sorry for my horrible attempt to explain :)

**Comment by jp7677** [comment]
Alright, actually I don’t mind if calls are a bit slower than logging in  wine (which is probably quite optimized). Logging is disabled by default now and all methods that should be in a hot path (d3d or fetching temperatures etc) should have the `alreadyLogged` construction. If not, please let me know where we would need to add more log spam protraction.

**Comment by jp7677** [comment]
Function names are now automated since https://github.com/jp7677/dxvk-nvapi/commit/2a4ebbd6ae03e20d7383bd2bdf9e7896d0500c16
