### ISSUE TITLE
Assassin’s Creed Odyssey complains about driver version

### ISSUE THREAD

**Issue by aufkrawall** [jp7677/dxvk-nvapi#50]
Despite of DXVK-NVAPI being used and DXVK configured accordingly, the game doesn't correctly identify the GPU driver and Ubisoft Connect overlay throws a warning pop up (which can be closed, so nothing dramatic):
![Screenshot_20211011_130428](https://user-images.githubusercontent.com/13510490/136783030-e7439a59-bb2a-46f5-8347-068a25fb4b94.png)

It also doesn't help to spoof my 3060 in DXVK config via `dxgi.customVendorId = 10de` `dxgi.customDeviceId = 2504`.

Not sure how the game actually queries driver information, i.e. if it is fixable in DXVK-NVAPI. But it does recognize `DXVK_NVAPI_DRIVER_VERSION=47212`.

**Comment by jp7677** [comment]
Could you please add logs from DXVK-NVAPI (See https://github.com/jp7677/dxvk-nvapi#debugging )?
May be that gives an idea if the GPU type is queried using nvapi.

**Comment by SveSop** [comment]
DXVK-NVAPI does not provide `*pSubSystemId` or `*pRevisionId` for `NvAPI_GPU_GetPCIIdentifiers`
It does somewhat seem a bit far fetched that manufacturer (Asus/MSI/whatever) should be relevant tho, but who knows?

@aufkrawall You could test my old implementation [https://github.com/SveSop/nvapi_standalone](https://github.com/SveSop/nvapi_standalone) (Just use the nvapi/nvapi64 dll's), and see what happens with this error. Be aware that it does not support much of the new stuff tho (like DLSS and whatnot).
If the driver error is gone then, it should be easy enough to implement, but it would require nvml usage.

**Comment by aufkrawall** [comment]
With that, the game displays the card's name, but the overlay still complains (apparently the game too, indicated by red driver version font):
![Screenshot_20211011_225543](https://user-images.githubusercontent.com/13510490/136854722-d925ebe8-c8b1-407a-9c65-352605e8a262.png)
It also doesn't list the display name anymore.

**Comment by jp7677** [comment]
Could you please also make a screenshot of GPU-Caps-Viewer with svesop’s nvapi?

**Comment by SveSop** [comment]
Why does it list 472.12? 470.74 is latest Linux driver.. or have you spoofed driver version to the same as Win10?

**Comment by SveSop** [comment]
Oki. The only other "get driver information from nvapi" (save from OTHER nvapi calls) seems to be something.. else :)

If i run GPUCapsViewer on my windows box this is what is shown for driver:
`R496.13(r495_86) / 30.0.14.9613 (10-6-2021)` (Yeah, new driver just now)

Interpretation of this is - Driver version: 496.13 - Branch: 495_86, and you can actually get the driver version from the nvapi.dll version shown last - 30.0.14.9613 = (30.0.1)4.9613. Maybe.. just maaaybe it is actually using the version of the nvapi.dll to get the version (or compare - to make sure that nvapi version matches the installed driver version)?

It could make sense to actually check that nvapi.dll is matching the driver version, since nvapi.dll could have functions mis-matching the driver if not.. dunno.. (and is my "suspicion"). Ill see if i can do some experimentation with this tomorrow.

**Comment by SveSop** [comment]
This was a wild guess that did not seem to pan out tbh. Next suspicion is ofc that there is some sort of versioning from the actual driver itself completely outside of nvapi. You can see on windows device manager on properties and under "Details", the "driver version" sais: 30.0.14.9613. Where Windows get this version from is unknown, but from the various dll's and sys files that make the nVidia driver (in various folders and whatnot), SOME of them is of this version.

Maybe it is some kind of check for this someplace? Was not able to figure it out.. 

Could implement this `*pSubSystemId` stuff via nvml, but i am not sure if it is interesting @jp7677 ? (Would require usage of nvml in the wineprefix).

**Comment by jp7677** [comment]
I've added a note about AC Odyssey in the wiki: https://github.com/jp7677/dxvk-nvapi/wiki/Quirks-for-usage-with-DXVK-NVAPI#assassins-creed-odyssey

**Comment by gofman** [comment]
The game uses wbemprox for actual version check, this commit (current in Proton Bleeding Edge only) should be fixing it both on Nvidia and AMD: https://github.com/ValveSoftware/wine/commit/b88b31334749955b0a9ded0c97fbbe4d759ff1ac

**Comment by jp7677** [comment]
Thanks a lot for finding this!
