### ISSUE TITLE
[Question] How can I use it in windows 10 ?

### ISSUE THREAD

**Issue by Milor123** [jp7677/dxvk-nvapi#63]
Hi guys, i am currently use DXVK in windows using the same that uses in linux for many games and help me too much, games newers like World war 3 (WW3) but in some cases i would like get more perfomance

Could I use it library in some games in windows 10? What should i do to try?

I aprovech for do a question out of this thread, is about of the new NATIVE library of DXVK for windows, it not work well for me in somegames, i prefer use the linux libraries

https://github.com/Joshua-Ashton/dxvk-native/releases/ (it work bad for my windows)
What should i use? Can i combine it or the original DXVK with your NVAPI libraries? 

Please help me, DXVK its great for me and allow me play in 60 fps or more with high or ultra settings in many games with my low specs gtx 1050ti and i7 4790k.

Thank u very much guys !!!!

**Comment by jp7677** [comment]
Hi. This depends on the game/application. 
If the game tries to find its dependencies in the working directory (usually the directory where the executable is) first, you can just place the `nvapi.dll` / `nvapi64.dll` in the working directory and it will be used instead of NVIDIA’s nvapi dlls. This is the same with DXVK.
If the game tries to find the nvapi dlls only in the system folders or directly from the location of the NVIDIA installer, then there is nothing you can do. Well, you could replace your nvapi dlls in the system folders, but I would strongly advice against it, this a pretty good way to break your system.

**Comment by jp7677** [comment]
About dxvk-native, from my understanding this project is for porting applications to Linux (native is native-Linux in this case), so not anything that is supposed to be used on Windows.

**Comment by SveSop** [comment]
@Milor123 
Using dxvk-nvapi in windows on a actual nvidia adapter would be rather pointless if you ask me. All this project is trying to do is emulate what the ACTUAL nvidia library is doing in windows. Why would you replace native nvidia made nvapi/nvapi64 with this "hack" when using windows?

DXVK used in Windows does sometimes provide better performance than Windows D3D9/11, so that is worth a try for sure.. but there is absolutely no point in using dxvk-nvapi together with DXVK. Somewhat of an overarching goal of THIS project (DXVK-NVAPI) is to provide the **SAME** functions as nVidia _native windows nvapi library_, but falls short in most functions.

**Comment by jp7677** [comment]
> @Milor123 Using dxvk-nvapi in windows on a actual nvidia adapter would be rather pointless if you ask me. All this project is trying to do is emulate what the ACTUAL nvidia library is doing in windows. Why would you replace native nvidia made nvapi/nvapi64 with this "hack" when using windows?
> 
> DXVK used in Windows does sometimes provide better performance than Windows D3D9/11, so that is worth a try for sure.. but there is absolutely no point in using dxvk-nvapi together with DXVK. Somewhat of an overarching goal of THIS project (DXVK-NVAPI) is to provide the **SAME** functions as nVidia _native windows nvapi library_, but falls short in most functions.

This is not entirely correct. I'm very certain that you'll need DXVK-NVAPI on Windows when you want to use DLSS or the (albeit not that significant) D3D11 extensions (SetDepthBoundsTest, UAVOverlap) together with DXVK or VKD3D-Prorton on Windows.  It is of course pointless to use DXVK-NVAPI without DXVK or VKD3D-Proton or just for the sysinfo entry points.

**Comment by jp7677** [comment]
I guess this question has been answered, please feel free to continue this discussion or ask more.

**Comment by Milor123** [comment]
@jp7677 @SveSop I am sincerely grateful for your response, thank you for explaining all this to me guys! Now i understand a few more

**Comment by SveSop** [comment]
> This is not entirely correct. I'm very certain that you'll need DXVK-NVAPI on Windows when you want to use DLSS or the (albeit not that significant) D3D11 extensions (SetDepthBoundsTest, UAVOverlap) together with DXVK or VKD3D-Prorton on Windows. It is of course pointless to use DXVK-NVAPI without DXVK or VKD3D-Proton or just for the sysinfo entry points.

I did not think it would not work, but you seem to be correct in that. I cant test for DLSS as i have a GTX970 card in my Win10 box, but i did test for NvAPI_D3D11_SetDepthBoundsTest in the MHO Benchmark. It uses D3D11 and SetDepthBoundsTest, and in wine/linux it yields around 1-2% increase to use dxvk-nvapi. Mostly within the margin of error, but nevertheless.

I tested the following in Windows 10:
```
DXVK(dxgi.nvapiHack = True) (Will fake AMD card and not use nvapi)
Score: 12826 - max: 58.3 min: 17.4

DXVK(dxgi.nvapiHack = False) + native nvapi
Score: 9822 - max: 44.8 min: 17.9

DXVK(dxgi.nvapiHack = False) + dxvk-nvapi
Score: 12918 - max: 58.7 min: 26.3

Native D3D11 + native nvapi
Score: 15214 - max: 69.2 min: 22.9
```
So it does seem as if you use nVidia native nvapi with DXVK when SetDepthBoundsTest is used, it will yield a worse performance (the reason the dxgi.nvapiHack setting came about in the first place, due to spamming non-working calls of this function will cause slowdowns). Using dxvk-nvapi gave a minor increase (wee bit less than 1%) over faking an AMD card, and i would say it is somewhat the same as i have seen in wine/linux

Native D3D11 beat DXVK for that particular benchmark, but that is not the case for all games/apps tho.

@Milor123 
I guess you just have to test on a per-game basis. I would however not think any resources will go into getting DXVK/vkd3d-proton optimized for windows 10 usage in particular tho, and i think the general stance on bug reports regarding Windows 10 usage of said libs usually ends up with "well, im sorry, but it is not really meant for that" :smile: 

Feel free to test a DLSS use-case aswell if any of you have the option... confirmation is always nice even if Jens most likely is correct in that instance aswell :smiley: 

Happy newyears!

**Comment by eebssk1** [comment]
For anyone still search for a way to load.
You can preload the nvapi libraries by using a proxy dll hooker like [Koaloader](https://github.com/acidicoala/Koaloader)
Works for me on Icarus.

**Comment by ablolba** [comment]
@eebssk1 How did you do that?

**Comment by ablolba** [comment]
@eebssk1 This is the first time I've heard of this.

 I'm trying to force DLSS in Robocop. The game starts, but it doesn't show any difference. I'm using VK3D Proton 2.14.1 with DXVK GPLasync 2.7

<img width="2362" height="1055" alt="Image" src="https://github.com/user-attachments/assets/04644b81-1c1d-47d4-8fa0-7fca0f438b84" />

Koaloader here is Version.dll (x64)

**Comment by eebssk1** [comment]
> [Koaloader.config.json](https://github.com/user-attachments/files/21334496/Koaloader.config.json) [Koaloader.log.log](https://github.com/user-attachments/files/21334497/Koaloader.log.log) [nvapi64-tests_dxgi.log](https://github.com/user-attachments/files/21334495/nvapi64-tests_dxgi.log) [RoboCopUnfinishedBusiness-Win64-Shipping_dxgi.log](https://github.com/user-attachments/files/21334498/RoboCopUnfinishedBusiness-Win64-Shipping_dxgi.log)
> 
> [@eebssk1](https://github.com/eebssk1) This is the first time I've heard of this.
> 
> I'm trying to force DLSS in Robocop. The game starts, but it doesn't show any difference. I'm using VK3D Proton 2.14.1 with DXVK GPLasync 2.7
> <img alt="Image" width="2000" height="1055" src="https://private-user-images.githubusercontent.com/167223743/468372741-04644b81-1c1d-47d4-8fa0-7fca0f438b84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMwMTMxMzMsIm5iZiI6MTc1MzAxMjgzMywicGF0aCI6Ii8xNjcyMjM3NDMvNDY4MzcyNzQxLTA0NjQ0YjgxLTFjMWQtNDdkNC04ZmEwLTdmY2EwZjQzOGI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyMFQxMjAwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Yjc1ZDk0ZWI5MGQ3YmIwYWI5YzI2ZTNlNjI0M2EyZGQwOWFjZTE0ZjZhNTEwOWUwNzM3YjZlMGUzODhmZTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tSglDr_kITbMl1-tlZkO6qUVPFQ6pAaPfwL8HUSEryo">
> 
> Koaloader here is Version.dll (x64)

You didn't specify any module to load in the config file.

**Comment by eebssk1** [comment]
> [@eebssk1](https://github.com/eebssk1) the game still can't see dlss
> 
> [Koaloader.config.json](https://github.com/user-attachments/files/21334857/Koaloader.config.json)

Use system informer(previous process hacker) to check if the game did load the custom nvapi dll.
if it does load but you still can not enable then probably the game use non-standard api or you dll replacement combination are incompatible.

**Comment by ablolba** [comment]
@eebssk1 Seems like it loaded both

<img width="701" height="130" alt="Image" src="https://github.com/user-attachments/assets/b6ac91df-4bd7-4875-a8ba-5994c1083133" />

<img width="725" height="96" alt="Image" src="https://github.com/user-attachments/assets/e380b311-db2b-4493-9991-2ccf9ec3320f" />

**Comment by alejandro097** [comment]
> > [@eebssk1](https://github.com/eebssk1) How did you do that?
> 
> you can use any dll hijack loader to load the dxvk nvapi dlls. like winhttp.dll winmm.dll proxy

this worked perfectly, thank you. Now I just need to find a way to change DLSS presets

**Comment by ablolba** [comment]
> > > [@eebssk1](https://github.com/eebssk1) How did you do that?
> > 
> > 
> > you can use any dll hijack loader to load the dxvk nvapi dlls. like winhttp.dll winmm.dll proxy
> 
> this worked perfectly, thank you. 

Can you show how you did that?
