### ISSUE TITLE
NvAPI_GPU_GetAdapterId From Physical Gpu returns error when nvidia card is not set as primary in bios setup.

### ISSUE THREAD

**Issue by pashachek** [jp7677/dxvk-nvapi#70]
NvAPI_GPU_GetAdapterId From Physical Gpu returns error when nvidia card is not set as primary in bios setup.

Hello! 
Initially I would like to say great thanks for your job!!! Gods bless you!

I have laptop with amd integrated and nvidia discrete gpu.

Playing with dlss feature in cyberpunk 2077 I found and issue.
When my nvidia card is set up as primary in bios it works fine. I mean cyberpunk detects dlss can be available.

But when I make my integrated amd card as primary in bios it causes NvApi error and  dlss is not available in cyberpunk.
For running lutris I use command: 
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only DXVK_FILTER_DEVICE_NAME="NVIDIA GeForce RTX 3060 Laptop GPU" lutris -d

opensuse tumbleweed , kernel 5.16.1-1
lutris 0.5.9.1
dxvk-nvapi v0.5.2
wine 7.0 staging or lutris-ge7-.0
nvidia rtx 3060

Logs are below.

[cp_log_nvidia_gpu_is_not_set_prime.txt](https://github.com/jp7677/dxvk-nvapi/files/7995934/cp_log_nvidia_gpu_is_not_set_prime.txt)
[cp_log_nv_set_prime.txt](https://github.com/jp7677/dxvk-nvapi/files/7995936/cp_log_nv_set_prime.txt)

**Comment by jp7677** [comment]
Thanks for the report.
I don't have such a setup to really be certain, but I'm pretty sure that your issue is with wine-vulkan not assigning a LUID to your adapter in the prime setup. You can verify this by running `vulkaninfo.exe` (thus the Windows executable from the Windows Vulkan SDK) with your wine version and look at the `deviceLUID` property.
This has been fixed for Proton with this commit https://github.com/ValveSoftware/wine/commit/0d00e4fc11f9768447f0544496e316edf225de84 which is in Proton 6.3 Experimental. Unfortunately I don't know if there is a wine version for Lutris  that ships this commit.

**Comment by pashachek** [comment]
Thanks a lot. I`ll check and will let you know

**Comment by jp7677** [comment]
Hi @pashachek , did you found some time to validate what i wrote?
