### ISSUE TITLE
Special K requires numerous undocumented (NDAed) NvAPI calls

### ISSUE THREAD

**Issue by ishitatsuyuki** [jp7677/dxvk-nvapi#72]
Special K is like the swiss army knife for modding things like game input or frame pacing. I'm interested as it has support for adding Reflex to basically every game, but it seems to do some very awkward checks against the NvAPI implementation. The Nvidia integrations does not activate without passing these checks.

It checks for the existence of the following functions, which according to them is "undocumented and only known to those who signed NDA" (why are they making fun of the NDA is another question):

```
NvAPI_GPU_GetRamType
NvAPI_GPU_GetFBWidthAndLocation
NvAPI_GPU_GetPCIEInfo
NvAPI_GetPhysicalGPUFromGPUID
NvAPI_GetGPUIDFromPhysicalGPU
```

See the full code [here](https://gitlab.aemony.se/Kaldaien/SpecialK/-/blob/92ac1d43d7b2ed86eb36ac0ad7bc601f14091bc3/src/nvapi.cpp#L1231).

Dealing with NDA related things sound like a good way to get legal trouble and get blackmailed by NV, so I wonder if it is within NvAPI's scope to implement these?

**Comment by ishitatsuyuki** [comment]
Actually, the mod disables the use of NvAPI completely under Wine. So I'll probably work with the upstream to resolve this issue.

I'll leave the issue open for the record.

**Comment by jp7677** [comment]
This project uses the headers from the official NVAPI Open Source SDK (https://download.nvidia.com/XFree86/nvapi-open-source-sdk/). The first three methods are not declared in there, so I cannot add those.
Looking through the Special K source code, I'm certain there are better ways to detect if you are running an NVIDIA card. So yeah, changing this upstream has likely a better chance to succeed.

**Comment by ishitatsuyuki** [comment]
OK. Closing.

**Comment by SveSop** [comment]
@ishitatsuyuki 
> 
> Dealing with NDA related things sound like a good way to get legal trouble and get blackmailed by NV, so I wonder if it is within NvAPI's scope to implement these?

This would probably not give any legal issues for individual implementation of this.. after all, wine-staging have had the nvapi implementation since way before NVIDIA even considered anything like opensource, and i have not really heard anything about huge legal battles with CodeWeavers/WineHQ vs NVIDIA around this.

However, when it comes to using NDA functions for Steam Proton, NVIDIA might be more interested, since this is somewhat of a money-making-machine 😄 Thus, it is wise to not upstream NDA functions with DXVK-NVAPI for use with Proton.

I have a couple of "unknown" functions i add to my own fork of dxvk-nvapi, so if it is of interest, i could perhaps pursue this more out of "just because", but have not really looked into Special K and its use.

I think that sometimes apps/games uses some sort of "default check" thing for NVAPI, because i can also see something similar to this happening with NVIDIA's own releases of UE4 demos that must be completely and utterly uninteresting to check for. I mean, there would be no point in doing nvapi calls for clock speeds and powermodes when running a small demo which have no information for said speeds onscreen.

Maybe the NDA version got some linker lib or whatnot that just run a "set amounts of tests"? (Not saying this is the case for Special K, since the source actually contains the calls and addresses that ARE under NDA - and thus.. could potentially be open to legal issues).
